###GET hello world!
GET https://cse-341-a8j3.onrender.com/

###GET all records
GET https://cse-341-a8j3.onrender.com/contacts

###GET onee record
GET http://localhost:8080/contacts


###POST Crreate user
POST http://localhost:8080/contacts
Content-Type: application/json

{
    "firstName": "Branislav",
    "lastName": "Bogosavac",
    "email": "bogosavac@gmail.com",
    "favoriteColor": "blue",
    "birthday": "14-08-2000"
  }