###GET hello world!
GET https://cse-341-a8j3.onrender.com/

###GET all records
GET https://cse-341-a8j3.onrender.com/contacts

###GET onee record
GET http://localhost:8080/contacts


###POST Crreate user
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Dmytro",
  "lastName": "Ivanytskyi",
  "email": "divanytskyi@gmail.com",
  "favoriteColor": "red",
  "birthday": "23-07-1998"
}


###PUT Crreate user
PUT http://localhost:8080/contacts/6676d5f02f57a20b9c44b86d
Content-Type: application/json

 {
  "firstName": "Dmytro updated 1",
  "lastName": "Ivanytskyi updated",
  "email": "divanytskyi@gmail.com",
  "favoriteColor": "red",
  "birthday": "23-07-1998"
}

###DELETE Crreate user
DELETE http://localhost:8080/contacts/6676dba0574ce7d51563f57c
