###GET hello world!
GET https://cse-341-a8j3.onrender.com/

###GET all records
GET https://cse-341-a8j3.onrender.com/contacts

###GET onee record
GET https://cse-341-a8j3.onrender.com/contacts/6676f32f9b51e792e510536c


###POST Crreate user
POST https://cse-341-a8j3.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Dmytro",
  "lastName": "Ivanytskyi",
  "email": "divanytskyi@gmail.com",
  "favoriteColor": "red",
  "birthday": "23-07-1998"
}


###PUT Crreate user
PUT https://cse-341-a8j3.onrender.com/contacts/6676f32f9b51e792e510536c
Content-Type: application/json

 {
  "firstName": "Dmytro updated 1",
  "lastName": "Ivanytskyi updated",
  "email": "divanytskyi@gmail.com",
  "favoriteColor": "red",
  "birthday": "23-07-1998"
}

###DELETE Crreate user
DELETE https://cse-341-a8j3.onrender.com/contacts/6676f32f9b51e792e510536c
