// PRODUCTION Deploy
## Get all book records
GET https://cse-341-project-2-cnxw.onrender.com/books

### Get book record by id
GET https://cse-341-project-2-cnxw.onrender.com/books/668043037655d52bf4025aa7

### Create book record
POST https://cse-341-project-2-cnxw.onrender.com/books HTTP/1.1
content-type: application/json

{
    "title": "Kobzar",
    "author": "Taras Shevchenko",
    "publishedDate": "1840-01-01",
    "genre": "Poetry",
    "country": "Ukraine"
}

### PUT book record
PUT https://cse-341-project-2-cnxw.onrender.com/books/668043037655d52bf4025aa7 HTTP/1.1
content-type: application/json

{
    "title": "Kobzar Updated",
    "author": "Taras Shevchenko Updated",
    "publishedDate": "1840-01-01",
    "genre": "Poetry",
    "country": "Ukraine"
}

### DELETE book record
DELETE https://cse-341-project-2-cnxw.onrender.com/books/668043037655d52bf4025aa7 HTTP/1.1


// LOCALHOST
### Get all book records
GET http://localhost:8080/books

### Get book record by id
GET http://localhost:8080/books/667fe6d19176da615092586

### Create book record
POST http://localhost:8080/books HTTP/1.1
content-type: application/json

{
    "title": "Kobzar",
    "author": "Taras Shevchenko",
    "publishedDate": "1840-01-01[]",
    "genre": "Poetry",
    "country": "Ukraine"
}

### PUT book record
PUT http://localhost:8080/books/667fe6d19176da6150925860 HTTP/1.1
content-type: application/json

{
    "title": "Kobzar Updated",
    "author": "Taras Shevchenko Updated",
    "publishedDate": "1840-01-01T00:00:00Z",
    "genre": "Poetry",
    "country": "Ukraine"
}

### DELETE book record
DELETE http://localhost:8080/books/667fe6d19176da6150925869 HTTP/1.1


### 404 NOT FOUND 
GET http://localhost:8080/not-found
